In [3]:
import numpy as np

## numpy.where()

In [16]:
a = np.array([10,2,5,8])
indices = np.where(a>2)
print(indices)
print(a[indices])

(array([0, 2, 3], dtype=int64),)
[10  5  8]


In [17]:
a[np.array([1,3])]

array([2, 8])