In [6]:
import numpy as np
a = np.random.randint(1,10,size=(2,3,4))
print(a)

[[[4 1 3 4]
  [6 8 4 6]
  [7 7 4 1]]

 [[2 3 7 9]
  [4 3 9 2]
  [9 1 3 4]]]


例子中我们的数组a是三维的，即每一个元素可写为 $a_{i,j,k}$。
在axis=m上操作, 表示对a的第m个下标进行操作。如这里对a的axis=0求和，就是 $\sum_i a_{i,:,:}$

In [14]:
print(np.sum(a,axis=0))

[[ 6  4 10 13]
 [10 11 13  8]
 [16  8  7  5]]


$\sum_j a_{:,j,:}$

In [12]:
print(np.sum(a,axis=1))

[[17 16 11 11]
 [15  7 19 15]]


$\sum_k a_{:,:,k}$

In [13]:
print(np.sum(a,axis=2))

[[12 24 19]
 [21 18 17]]
